services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/bin/bash"
    stdin_open: true
    tty: true
    container_name: kopi_app
    ports:
      - "8080:8080"
  mongo:
    image: mongo:6.0
    container_name: kopi_mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    #   MONGO_INITDB_DATABASE: kopi
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  app:
  mongo_data:
