services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/bin/bash"
    stdin_open: true
    tty: true
    container_name: kopi_app
    ports:
      - "8080:8080"
    volumes:
      - ./:/workspace

volumes:
  app:
  mongo_data:
